openapi: 3.0.0
info:
  title: Cart API Documentation
  version: 1.0.0
  description: API documentation for the cart module

paths:
  /cart:
    get:
      summary: Retrieve the cart
      tags: [Cart]
      responses:
        "200":
          description: The cart object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'

  /cart:
    post:
      summary: Add an item to the cart
      tags: [Cart]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                  description: The ID of the product
                quantity:
                  type: integer
                  description: The quantity of the product
      responses:
        "201":
          description: Item added to the cart

components:
  schemas:
    Cart:
      type: object
      properties:
        products:
          type: array
          items:
            type: object
            properties:
              product:
                $ref: '#/components/schemas/Product'
              quantity:
                type: integer
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        code:
          type: string
        price:
          type: number
        stock:
          type: number
        category:
          type: string
        status:
          type: boolean
        thumbnail:
          type: array
          items:
            type: string
